### ISSUE TITLE
production switchover checklist

### ISSUE THREAD

**Issue by mr-c** [ProteinsWebTeam/ebi-metagenomics-cwl#68]
- [ ] chunking of outputs 
- [ ] scatter & chunking for other steps, perhaps
- [ ] running on OpenLava 
- [ ] replication at another site
  - [ ] prepare by confirming that all needed scripts are copied out of existing pipeline)
- [ ] run new dataset through CWL v3 inclusive of upload to website
